server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/rent_service
    password: 123456
  redis:
    host: localhost
    port: 6379

jpa:
  hibernate:
    ddl-auto: none
    show-sql: true
    open-in-view: true
springdoc:
  swagger-ui:
    path=/swagger-ui-custom:
      html:
#okta:
#  oauth2:
#    # Replace with the domain of your Auth0 tenant.
#    issuer: https://dev-2iuikzj50eqgyhsr.us.auth0.com/
#    # Replace with the API Identifier for your Auth0 API.
#    audience: https://demo/api






