version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"